# Generated by Django 4.0.4 on 2022-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_first_msg',
            field=models.BooleanField(default=True),
        ),
    ]
