# Generated by Django 4.0.4 on 2022-05-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_thread_is_first_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='first_person_send',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='thread',
            name='second_person_send',
            field=models.BooleanField(default=False),
        ),
    ]
