# Generated by Django 4.0.4 on 2022-05-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_thread_first_person_send_thread_second_person_send'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='first_sender_id',
            field=models.IntegerField(default=0),
        ),
    ]
