# Generated by Django 4.0.4 on 2022-05-09 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_thread_first_sender_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first_sender_id',
        ),
        migrations.AddField(
            model_name='thread',
            name='first_sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
