# Generated by Django 4.0.4 on 2022-05-14 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_thread_first_sender_id_thread_first_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='first_person_send',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='second_person_send',
        ),
    ]
